# UG 带边界面铣基础实例创建

## 代码功能概述
创建基础工序，完成飞面。

## 核心代码解释

### 获取会话与工作部件

```cpp
#include <NXOpen/Session.hxx>
#include <NXOpen/Part.hxx>
#include <NXOpen/PartCollection.hxx>

NXOpen::Session* theSession = NXOpen::Session::GetSession();
NXOpen::Part* workPart = theSession->Parts()->Work();
```

### 获取程序组、方法、刀具、几何体
```cpp
#include<NXOpen/CAM_CAMSetup.hxx>
#include<NXOpen/CAM_NCGroupCollection.hxx>
#include<NXOpen/CAM_NCGroup.hxx>
#include<NXOpen/CAM_Method.hxx>

const char* programGroupName = "PROGRAM";
NXOpen::CAM::NCGroup* programGroup(dynamic_cast<NXOpen::CAM::NCGroup*>(workPart->CAMSetup()->CAMGroupCollection()->FindObject(programGroupName)));
NXOpen::CAM::Method* method(dynamic_cast<NXOpen::CAM::Method*>(workPart->CAMSetup()->CAMGroupCollection()->FindObject("METHOD")));
NXOpen::CAM::NCGroup* cuttingtool(dynamic_cast<NXOpen::CAM::NCGroup*>(workPart->CAMSetup()->CAMGroupCollection()->FindObject("NONE")));
NXOpen::CAM::NCGroup* geometry(dynamic_cast<NXOpen::CAM::NCGroup*>(workPart->CAMSetup()->CAMGroupCollection()->FindObject("NONE")));
```

### 创建面铣操作
```cpp
#include<NXOpen/CAM_Operation.hxx>
#include<NXOpen/CAM_OperationCollection.hxx>
#include<NXOpen/CAM_FaceMilling.hxx>

NXOpen::CAM::Operation* operation;
operation = workPart->CAMSetup()->CAMOperationCollection()->Create(
    programGroup,
    method,
    cuttingtool,
    geometry,
    "mill_planar",
    "FACE_MILLING",
    NXOpen::CAM::OperationCollection::UseDefaultNameTrue,
    "FACE_MILLING");
NXOpen::CAM::FaceMilling* faceMillingOperation(dynamic_cast<NXOpen::CAM::FaceMilling*>(operation));
```

### 创建面铣构造器并实例化构造器
```cpp
#include<NXOpen/CAM_FaceMillingBuilder.hxx>

NXOpen::CAM::FaceMillingBuilder* faceMillingOperationBuilder;
faceMillingOperationBuilder = workPart->CAMSetup()->CAMOperationCollection()->CreateFaceMillingBuilder(faceMillingOperation);
```

### 设置切削参数
```cpp
#include<NXOpen/CAM_MillOperationBuilder.hxx>
#include<NXOpen/CAM_MillCutParameters.hxx>

// 设置切削参数，选中延伸到部件轮廓
faceMillingOperationBuilder->CutParameters()->SetExtendToPart(true);
```
在切削参数，策略中。

<img src="./images/面铣延伸到部件轮廓.png">

## 完整代码
```cpp
#include <uf_defs.h>
#include <NXOpen/Session.hxx>
#include <NXOpen/Part.hxx>
#include <NXOpen/PartCollection.hxx>
#include<NXOpen/CAM_CAMSetup.hxx>
#include<NXOpen/CAM_NCGroupCollection.hxx>
#include<NXOpen/CAM_NCGroup.hxx>
#include<NXOpen/CAM_Method.hxx>
#include<NXOpen/CAM_Operation.hxx>
#include<NXOpen/CAM_OperationCollection.hxx>
#include<NXOpen/CAM_FaceMilling.hxx>
#include<NXOpen/CAM_FaceMillingBuilder.hxx>
#include<NXOpen/CAM_MillOperationBuilder.hxx>
#include<NXOpen/CAM_MillCutParameters.hxx>

extern "C" DllExport int ufusr_ask_unload()
{
    return (int)NXOpen::Session::LibraryUnloadOptionImmediately;
}

extern "C" DllExport void ufusr(char* param, int* retCode, int paramLen)
{
    // 获取会话与工作部件
    // Session::GetSession() 返回 PartCollection
    NXOpen::Session* theSession = NXOpen::Session::GetSession();
    // PartCollection-> Work() 返回 Part
    NXOpen::Part* workPart = theSession->Parts()->Work();

    // 程序组名
    // 刀具
    // 几何体
    // 方法
    // 类型
    // 具体工序
    const char* programGroupName = "PROGRAM";
    NXOpen::CAM::NCGroup* programGroup(dynamic_cast<NXOpen::CAM::NCGroup*>(workPart->CAMSetup()->CAMGroupCollection()->FindObject(programGroupName)));
    NXOpen::CAM::Method* method(dynamic_cast<NXOpen::CAM::Method*>(workPart->CAMSetup()->CAMGroupCollection()->FindObject("METHOD")));
    NXOpen::CAM::NCGroup* cuttingtool(dynamic_cast<NXOpen::CAM::NCGroup*>(workPart->CAMSetup()->CAMGroupCollection()->FindObject("NONE")));
    NXOpen::CAM::NCGroup* geometry(dynamic_cast<NXOpen::CAM::NCGroup*>(workPart->CAMSetup()->CAMGroupCollection()->FindObject("NONE")));

    NXOpen::CAM::Operation* operation;
    operation = workPart->CAMSetup()->CAMOperationCollection()->Create(
        programGroup,
        method,
        cuttingtool,
        geometry,
        "mill_planar",
        "FACE_MILLING",
        NXOpen::CAM::OperationCollection::UseDefaultNameTrue,
        "FACE_MILLING");

    NXOpen::CAM::FaceMilling* faceMillingOperation(dynamic_cast<NXOpen::CAM::FaceMilling*>(operation));
    NXOpen::CAM::FaceMillingBuilder* faceMillingOperationBuilder;
    faceMillingOperationBuilder = workPart->CAMSetup()->CAMOperationCollection()->CreateFaceMillingBuilder(faceMillingOperation);

    // 设置切削参数，选中延伸到部件轮廓
    faceMillingOperationBuilder->CutParameters()->SetExtendToPart(true);

    faceMillingOperationBuilder->Commit();

    faceMillingOperationBuilder->Destroy();
}
```