# UG 底壁铣二次开发基础代码阅读文档

## 代码功能概述

该代码用于在 UG 软件中创建一个底壁铣的操作工序，并将其中的步距参数改为刀路数。

<img src='./images/底壁铣步距参数.png'>

## 代码实现步骤

### 获取会话与工作部件

```cpp
NXOpen::Session* theSession = NXOpen::Session::GetSession();
NXOpen::Part* workPart = theSession->Parts()->Work();
```

通过调用 `NXOpen::Session::GetSession()` 获取当前 UG 会话，然后通过 `theSession->Parts()->Work()` 获取当前工作部件。

### 获取程序组、方法、刀具、几何体

```cpp
const char* programGroupName = "PROGRAM";
NXOpen::CAM::NCGroup* programGroup(dynamic_cast<NXOpen::CAM::NCGroup*>(workPart->CAMSetup()->CAMGroupCollection()->FindObject(programGroupName)));
NXOpen::CAM::Method* method(dynamic_cast<NXOpen::CAM::Method*>(workPart->CAMSetup()->CAMGroupCollection()->FindObject("METHOD")));
NXOpen::CAM::NCGroup* cuttingtool(dynamic_cast<NXOpen::CAM::NCGroup*>(workPart->CAMSetup()->CAMGroupCollection()->FindObject("NONE")));
NXOpen::CAM::NCGroup* geometry(dynamic_cast<NXOpen::CAM::NCGroup*>(workPart->CAMSetup()->CAMGroupCollection()->FindObject("NONE")));
```

从工作部件的 CAM 设置中获取程序组、方法、刀具和几何体。程序组、方法、刀具和几何体分别通过调用 `workPart->CAMSetup()->CAMGroupCollection()->FindObject()` 方法获取，并使用 `dynamic_cast` 进行类型转换。

### 创建操作

```cpp
NXOpen::CAM::Operation* operation;
operation = workPart->CAMSetup()->CAMOperationCollection()->Create(
    programGroup,
    method,
    cuttingtool,
    geometry,
    "mill_planar",
    "FLOOR_WALL",
    NXOpen::CAM::OperationCollection::UseDefaultNameTrue,
    "FLOOR_WALL");
```

使用 `workPart->CAMSetup()->CAMOperationCollection()->Create()` 方法创建一个新的底壁铣操作。该方法的参数包括程序组、方法、刀具、几何体以及操作的类型和子类型等。

### 创建体积基的 2.5D 铣削操作构建器

```cpp
NXOpen::CAM::VolumeBased25DMillingOperation* volumeBased25DMillingOperation(dynamic_cast<NXOpen::CAM::VolumeBased25DMillingOperation*>(operation));
NXOpen::CAM::VolumeBased25DMillingOperationBuilder* volumeBased25DMillingOperationBuilder;
volumeBased25DMillingOperationBuilder = workPart->CAMSetup()->CAMOperationCollection()->CreateVolumeBased25dMillingOperationBuilder(volumeBased25DMillingOperation);
```

将创建的操作动态转换为 `NXOpen::CAM::VolumeBased25DMillingOperation` 类型，并通过 `workPart->CAMSetup()->CAMOperationCollection()->CreateVolumeBased25dMillingOperationBuilder()` 方法创建体积基的 2.5D 铣削操作构建器。

### 设置步距类型为刀路数

```cpp
volumeBased25DMillingOperationBuilder->BndStepover()->SetStepoverType(NXOpen::CAM::StepoverBuilder::StepoverTypesNumber);
```

通过调用 `volumeBased25DMillingOperationBuilder->BndStepover()->SetStepoverType()` 方法将步距类型设置为刀路数。

### 提交修改并销毁构建器

```cpp
volumeBased25DMillingOperationBuilder->Commit();
volumeBased25DMillingOperationBuilder->Destroy();
```

调用 `volumeBased25DMillingOperationBuilder->Commit()` 方法提交对操作的修改，并使用 `volumeBased25DMillingOperationBuilder->Destroy()` 方法销毁构建器，释放相关资源。

## 代码总结

该代码实现了在 UG 软件中创建一个底壁铣操作工序，并将其步距参数改为刀路数的功能。通过获取会话与工作部件、程序组、方法、刀具、几何体等信息，创建操作并设置相关参数，最终提交修改并清理资源。该代码可以帮助用户快速生成底壁铣操作，提高加工效率和自动化程度。

## 完整代码

```cpp
#include <uf_defs.h>
#include <NXOpen/Session.hxx>
#include <NXOpen/Part.hxx>
#include <NXOpen/PartCollection.hxx>
#include<NXOpen/CAM_CAMSetup.hxx>
#include<NXOpen/CAM_NCGroupCollection.hxx>
#include<NXOpen/CAM_NCGroup.hxx>
#include<NXOpen/CAM_Method.hxx>
#include<NXOpen/CAM_Operation.hxx>
#include<NXOpen/CAM_OperationCollection.hxx>
#include<NXOpen/CAM_VolumeBased25DMillingOperation.hxx>
#include<NXOpen/CAM_VolumeBased25DMillingOperationBuilder.hxx>
#include<NXOpen/CAM_PlanarOperationBuilder.hxx>
#include<NXOpen/CAM_StepoverBuilder.hxx>




extern "C" DllExport int ufusr_ask_unload()
{
    return (int)NXOpen::Session::LibraryUnloadOptionImmediately;
}

extern "C" DllExport void ufusr(char* param, int* retCode, int paramLen)
{
    // 获取会话与工作部件
    // Session::GetSession() 返回 PartCollection
    NXOpen::Session* theSession = NXOpen::Session::GetSession();
    // PartCollection-> Work() 返回 Part
    NXOpen::Part* workPart = theSession->Parts()->Work();

    // 程序组名
    // 刀具
    // 几何体
    // 方法
    // 类型
    // 具体工序

    /**
    * 获取程序组
    * NXOpen::CAM::CAMSetup* CAMSetup();
    * CAM_CAMSetup.hxx
    * 
    * NXOpen::CAM::NCGroupCollection* CAMGroupCollection();   
    * CAM_NCGroupCollection.hxx
    * 
    * NXOpen::CAM::NCGroup* FindObject(const NXString &sid)();
    * NXOpen::CAM::NCGroup* FindObject(const char *sid)();
    * CAM_NCGroup.hxx
    */
    const char* programGroupName = "PROGRAM";
    NXOpen::CAM::NCGroup* programGroup(dynamic_cast<NXOpen::CAM::NCGroup*>(workPart->CAMSetup()->CAMGroupCollection()->FindObject(programGroupName)));
    NXOpen::CAM::Method* method(dynamic_cast<NXOpen::CAM::Method*>(workPart->CAMSetup()->CAMGroupCollection()->FindObject("METHOD")));
    NXOpen::CAM::NCGroup* cuttingtool(dynamic_cast<NXOpen::CAM::NCGroup*>(workPart->CAMSetup()->CAMGroupCollection()->FindObject("NONE")));
    NXOpen::CAM::NCGroup* geometry(dynamic_cast<NXOpen::CAM::NCGroup*>(workPart->CAMSetup()->CAMGroupCollection()->FindObject("NONE")));

    NXOpen::CAM::Operation* operation;
    // operation1 = workPart->CAMSetup()->CAMOperationCollection()->Create(nCGroup1, method1, nCGroup2, nCGroup3, "mill_planar", "FLOOR_WALL", NXOpen::CAM::OperationCollection::UseDefaultNameTrue, "FLOOR_WALL");
    /**
    * NXOpen::CAM::OperationCollection* CAMOperationCollection();
    * CAM_OperationCollection.hxx
    * 
    * Create() 可以看源码基本上都是与Create相关的函数
    * 返回NXOpen::CAM::Operation
    * 在父组下创建指定类型和子类型的操作。
    */
    operation = workPart->CAMSetup()->CAMOperationCollection()->Create(
        programGroup,
        method,
        cuttingtool,
        geometry,
        "mill_planar",
        "FLOOR_WALL",
        NXOpen::CAM::OperationCollection::UseDefaultNameTrue,
        "FLOOR_WALL");

    // 基于体积的2.5D铣削操作 VolumeBased25DMillingOperation


    NXOpen::CAM::VolumeBased25DMillingOperation* volumeBased25DMillingOperation(dynamic_cast<NXOpen::CAM::VolumeBased25DMillingOperation*>(operation));
    NXOpen::CAM::VolumeBased25DMillingOperationBuilder* volumeBased25DMillingOperationBuilder;
    volumeBased25DMillingOperationBuilder = workPart->CAMSetup()->CAMOperationCollection()->CreateVolumeBased25dMillingOperationBuilder(volumeBased25DMillingOperation);

    // BndStepover在volumeBased25DMillingOperationBuilder的父父类中 
    // 参数设置， 步距设置为刀路数， 值为默认
    volumeBased25DMillingOperationBuilder->BndStepover()->SetStepoverType(NXOpen::CAM::StepoverBuilder::StepoverTypesNumber);
    volumeBased25DMillingOperationBuilder->Commit();

    volumeBased25DMillingOperationBuilder->Destroy();
}


```