# 面铣、型腔铣、深度轮廓铣、孔铣基本实例创建

TODO:在孔铣中，切削参数无法正确设置，待解决

视频链接：<a href="https://www.bilibili.com/video/BV1wjLAzPEx3/?spm_id_from=333.1387.homepage.video_card.click">UG半自动工序生成，非AI</a>

```cpp
#include <uf_defs.h>
#include <NXOpen/Session.hxx>
//#include <NXOpen/Axis.hxx>
//#include <NXOpen/BasePart.hxx>
//#include <NXOpen/Builder.hxx>
//#include <NXOpen/CAM_AcrossVoids.hxx>
//#include <NXOpen/CAM_ArcOutputTypeCiBuilder.hxx>

//#include <NXOpen/CAM_CAMSetup.hxx>
#include <NXOpen/CAM_CavityMilling.hxx>
#include <NXOpen/CAM_CavityMillingBuilder.hxx>



//#include <NXOpen/CAM_CutDirection.hxx>
#include <NXOpen/CAM_CutLevel.hxx>
//#include <NXOpen/CAM_CutParameters.hxx>
#include <NXOpen/CAM_CutPatternBuilder.hxx>
//#include <NXOpen/CAM_CutVolumeGeom.hxx>
//#include <NXOpen/CAM_Cycle.hxx>
#include <NXOpen/CAM_CylinderMilling.hxx>
#include <NXOpen/CAM_CylinderMillingBuilder.hxx>
#include <NXOpen/CAM_CylinderMillingCutParameters.hxx>
#include <NXOpen/CAM_CylindricalMillingBuilder.hxx>
#include <NXOpen/CAM_CylindricalMillingCutParameters.hxx>
//#include <NXOpen/CAM_DimensionRule.hxx>
//#include <NXOpen/CAM_DisplayPaint.hxx>
//#include <NXOpen/CAM_DisplayPath.hxx>
//#include <NXOpen/CAM_DisplaySilhouette.hxx>
//#include <NXOpen/CAM_DisplayTool.hxx>
//#include <NXOpen/CAM_ExtendAtEdges.hxx>
#include <NXOpen/CAM_FaceMilling.hxx>
#include <NXOpen/CAM_FaceMillingBuilder.hxx>
//#include <NXOpen/CAM_FeedsBuilder.hxx>
//#include <NXOpen/CAM_FeedsOptimizationData.hxx>
//#include <NXOpen/CAM_FinishPassesBuilder.hxx>
//#include <NXOpen/CAM_Geometry.hxx>
//#include <NXOpen/CAM_GeometryCiBuilder.hxx>
//#include <NXOpen/CAM_GeometrySet.hxx>
//#include <NXOpen/CAM_GeometrySetList.hxx>
//#include <NXOpen/CAM_HoleBossGeom.hxx>
//#include <NXOpen/CAM_HoleBossSet.hxx>
//#include <NXOpen/CAM_HoleBossSetList.hxx>
//#include <NXOpen/CAM_HoleMachiningBuilder.hxx>
//#include <NXOpen/CAM_HoleMachiningCutParameters.hxx>
//#include <NXOpen/CAM_Inheritable2dLength.hxx>
//#include <NXOpen/CAM_InheritableDoubleBuilder.hxx>
//#include <NXOpen/CAM_InheritableFeedBuilder.hxx>
//#include <NXOpen/CAM_InheritableFeedModeBuilder.hxx>
//#include <NXOpen/CAM_InheritableIntBuilder.hxx>
//#include <NXOpen/CAM_InheritableTextBuilder.hxx>
#include <NXOpen/CAM_InheritableToolDepBuilder.hxx>
//#include <NXOpen/CAM_LayoutCiBuilder.hxx>
#include <NXOpen/CAM_LevelToLevel.hxx>
//#include <NXOpen/CAM_LowerLimit.hxx>
//#include <NXOpen/CAM_MaxCutTraverse.hxx>
#include <NXOpen/CAM_Method.hxx>
#include <NXOpen/CAM_MillCutParameters.hxx>
//#include <NXOpen/CAM_MillOperationBuilder.hxx>
//#include <NXOpen/CAM_MinCutVolume.hxx>
//#include <NXOpen/CAM_MultiBladeBaseGeometry.hxx>
//#include <NXOpen/CAM_MultiBladeSplittersGeometry.hxx>
//#include <NXOpen/CAM_MultiDepthCut.hxx>
//#include <NXOpen/CAM_MultipleStepoverBuilder.hxx>
//#include <NXOpen/CAM_NCGroup.hxx>
#include <NXOpen/CAM_NCGroupCollection.hxx>
//#include <NXOpen/CAM_NcmAvoidancePointBuilder.hxx>
//#include <NXOpen/CAM_NcmClearanceBuilder.hxx>
#include <NXOpen/CAM_NcmHoleMachining.hxx>
#include <NXOpen/CAM_NcmHoleMachiningEngRet.hxx>
//#include <NXOpen/CAM_NcmPlanarBuilder.hxx>
//#include <NXOpen/CAM_NcmPlanarEngRetBuilder.hxx>
//#include <NXOpen/CAM_NcmSmoothingBuilder.hxx>
//#include <NXOpen/CAM_NcmSubopBuilder.hxx>
//#include <NXOpen/CAM_NcmTransfer.hxx>
//#include <NXOpen/CAM_NcmTransferBuilder.hxx>
//#include <NXOpen/CAM_Notes.hxx>
#include <NXOpen/CAM_Operation.hxx>
#include <NXOpen/CAM_OperationBuilder.hxx>
#include <NXOpen/CAM_OperationCollection.hxx>
//#include <NXOpen/CAM_OperationDisplayOptionsBuilder.hxx>
//#include <NXOpen/CAM_OppositeDirection.hxx>
//#include <NXOpen/CAM_OutputUncutRegions.hxx>


//#include <NXOpen/CAM_PlanarOperationBuilder.hxx>
//#include <NXOpen/CAM_PostEventsCiBuilder.hxx>
//#include <NXOpen/CAM_RoundPointBuilder.hxx>
//#include <NXOpen/CAM_SmallAreaAvoidance.hxx>
//#include <NXOpen/CAM_Splitter.hxx>
//#include <NXOpen/CAM_SplitterList.hxx>
//#include <NXOpen/CAM_SpunOutlineGeom.hxx>
//#include <NXOpen/CAM_SteepContainment.hxx>
//#include <NXOpen/CAM_StepoverBuilder.hxx>
//#include <NXOpen/CAM_StockPerPassBuilder.hxx>
//#include <NXOpen/CAM_ThreadedBossSet.hxx>
//#include <NXOpen/CAM_ThreadedBossSetList.hxx>
//#include <NXOpen/CAM_ThreadedHoleSet.hxx>
//#include <NXOpen/CAM_ThreadedHoleSetList.hxx>
//#include <NXOpen/CAM_Tool.hxx>
//#include <NXOpen/CAM_ToolAxisBase.hxx>

//#include <NXOpen/CAM_VerticalPosition.hxx>
//#include <NXOpen/CAM_ZAxisSmoothing.hxx>
#include <NXOpen/CAM_ZLevelMilling.hxx>
#include <NXOpen/CAM_ZLevelMillingBuilder.hxx>


//#include <NXOpen/Part.hxx>
#include <NXOpen/PartCollection.hxx>








extern "C" DllExport int ufusr_ask_unload()
{
    return (int)NXOpen::Session::LibraryUnloadOptionImmediately;
}

extern "C" DllExport void ufusr(char* param, int* retCode, int paramLen)
{
    // 获取会话与工作部件
    // Session::GetSession() 返回 PartCollection
    NXOpen::Session* theSession = NXOpen::Session::GetSession();
    // PartCollection-> Work() 返回 Part
    NXOpen::Part* workPart = theSession->Parts()->Work();

    // 程序组名
    // 刀具
    // 几何体
    // 方法
    // 类型
    // 具体工序

    // 1、 基础信息
    const char* programGroupName = "PROGRAM";
    NXOpen::CAM::NCGroup* programGroup(dynamic_cast<NXOpen::CAM::NCGroup*>(workPart->CAMSetup()->CAMGroupCollection()->FindObject(programGroupName)));
    NXOpen::CAM::Method* method(dynamic_cast<NXOpen::CAM::Method*>(workPart->CAMSetup()->CAMGroupCollection()->FindObject("METHOD")));
    NXOpen::CAM::NCGroup* cuttingtool(dynamic_cast<NXOpen::CAM::NCGroup*>(workPart->CAMSetup()->CAMGroupCollection()->FindObject("NONE")));
    NXOpen::CAM::NCGroup* geometry(dynamic_cast<NXOpen::CAM::NCGroup*>(workPart->CAMSetup()->CAMGroupCollection()->FindObject("NONE")));

    // 2、 操作创建
    /**
    * 面铣、型腔铣、深度轮廓铣、孔铣
    */
    NXOpen::CAM::Operation* faceMillingOperation;

    faceMillingOperation = workPart->CAMSetup()->CAMOperationCollection()->Create(
        programGroup,
        method,
        cuttingtool,
        geometry,
        "mill_planar",
        "FACE_MILLING",
        NXOpen::CAM::OperationCollection::UseDefaultNameTrue,
        "FACE_MILLING_new");


    NXOpen::CAM::FaceMilling* faceMilling(dynamic_cast<NXOpen::CAM::FaceMilling*>(faceMillingOperation));
    
    NXOpen::CAM::FaceMillingBuilder* faceMillingBuilder;
    faceMillingBuilder = workPart->CAMSetup()->CAMOperationCollection()->CreateFaceMillingBuilder(faceMilling);

    // 切削模式设置为往复
    faceMillingBuilder->CutPattern()->SetCutPattern(NXOpen::CAM::CutPatternBuilder::TypesZigZag);

    faceMillingBuilder->CutParameters()->SetExtendToPart(true);

    faceMillingBuilder->CutParameters()->SetSimplifyShapes(NXOpen::CAM::CutParametersSimplifyShapesTypesMinimumBox);

    faceMillingBuilder->Commit();

    faceMillingBuilder->Destroy();

    // 型腔铣
    NXOpen::CAM::Operation* cavityMillOperation;
    cavityMillOperation = workPart->CAMSetup()->CAMOperationCollection()->Create(
        programGroup,
        method,
        cuttingtool,
        geometry,
        "mill_contour",
        "CAVITY_MILL",
        NXOpen::CAM::OperationCollection::UseDefaultNameTrue,
        "CAVITY_MILL_new");

    NXOpen::CAM::CavityMilling* cavityMilling(dynamic_cast<NXOpen::CAM::CavityMilling*>(cavityMillOperation));
    NXOpen::CAM::CavityMillingBuilder* cavityMillingBuilder;
    cavityMillingBuilder = workPart->CAMSetup()->CAMOperationCollection()->CreateCavityMillingBuilder(cavityMilling);

    // 跟随周边
    cavityMillingBuilder->CutPattern()->SetCutPattern(NXOpen::CAM::CutPatternBuilder::TypesFollowPeriphery);
    // ap
    cavityMillingBuilder->CutLevel()->GlobalDepthPerCut()->DistanceBuilder()->SetValue(1.0);
    // 深度优先
    cavityMillingBuilder->CutParameters()->SetCutOrder(NXOpen::CAM::CutParametersCutOrderTypesDepthFirst);
    // 向内
    cavityMillingBuilder->CutParameters()->SetPatternDirection(NXOpen::CAM::CutParametersPatternDirectionTypesInward);
    // 岛清理
    cavityMillingBuilder->SetIslandCleanup(true);
    // 余量
    cavityMillingBuilder->CutParameters()->PartStock()->SetValue(0.20000000000000001);

    cavityMillingBuilder->Commit();
    cavityMillingBuilder->Destroy();

    // 深度轮廓铣
    NXOpen::CAM::Operation* zLevelMillingOperation;
    zLevelMillingOperation = workPart->CAMSetup()->CAMOperationCollection()->Create(
        programGroup,
        method,
        cuttingtool,
        geometry,
        "mill_contour",
        "ZLEVEL_PROFILE",
        NXOpen::CAM::OperationCollection::UseDefaultNameTrue,
        "ZLEVEL_PROFILE_new");

    NXOpen::CAM::ZLevelMilling* zLevelMilling(dynamic_cast<NXOpen::CAM::ZLevelMilling*>(zLevelMillingOperation));
    NXOpen::CAM::ZLevelMillingBuilder* zLevelMillingBuilder;
    zLevelMillingBuilder = workPart->CAMSetup()->CAMOperationCollection()->CreateZlevelMillingBuilder(zLevelMilling);

    // ap
    zLevelMillingBuilder->CutLevel()->GlobalDepthPerCut()->DistanceBuilder()->SetValue(0.20000000000000001);
    // 沿形状斜进刀
    zLevelMillingBuilder->CutParameters()->LevelToLevel()->SetType(NXOpen::CAM::LevelToLevel::TypesRampOnPart);
    // 角度 2
    zLevelMillingBuilder->CutParameters()->LevelToLevel()->RampAngle()->SetValue(2.0);

    zLevelMillingBuilder->Commit();
    zLevelMillingBuilder->Destroy();

    // ---------------------------------------------------------------
    // 孔铣
    NXOpen::CAM::Operation* cylinderMillingOperation;
    cylinderMillingOperation = workPart->CAMSetup()->CAMOperationCollection()->Create(
        programGroup,
        method,
        cuttingtool,
        geometry,
        "mill_planar",
        "HOLE_MILLING",
        NXOpen::CAM::OperationCollection::UseDefaultNameTrue,
        "HOLE_MILLING_new");

    NXOpen::CAM::CylinderMilling* cylinderMilling(dynamic_cast<NXOpen::CAM::CylinderMilling*>(cylinderMillingOperation));
    NXOpen::CAM::CylinderMillingBuilder* cylinderMillingBuilder;
    cylinderMillingBuilder = workPart->CAMSetup()->CAMOperationCollection()->CreateCylinderMillingBuilder(cylinderMilling);

    

    // 螺旋
    cylinderMillingBuilder->SetCutPattern(NXOpen::CAM::CylinderMillingBuilder::CutPatternTypesHelicalAndSpiral);
    // 螺旋直径
    cylinderMillingBuilder->SetDiameterForHelix(NXOpen::CAM::CylinderMillingBuilder::DiameterForHelixTypesDiameter);
    // 刀轨设置 80%刀具
    cylinderMillingBuilder->HelixDiameter()->SetIntent(NXOpen::CAM::ParamValueIntentToolDep); //mm
    cylinderMillingBuilder->HelixDiameter()->SetValue(80.0); // value

    cylinderMillingBuilder->AxialDistance()->SetValue(0.5);

    cylinderMillingBuilder->AxialDistance()->SetIntent(NXOpen::CAM::ParamValueIntentPartUnits);

    cylinderMillingBuilder->RadialStepover()->DistanceBuilder()->SetValue(0.5);

    cylinderMillingBuilder->RadialStepover()->DistanceBuilder()->SetIntent(NXOpen::CAM::ParamValueIntentPartUnits);



    // ----------------------------------------------
    //   Dialog Begin 切削参数
    // ----------------------------------------------

    cylinderMillingBuilder->MinimumHelixDiameter()->SetValue(80.0000000000000001);
    cylinderMillingBuilder->MinimumHelixDiameter()->SetIntent(NXOpen::CAM::ParamValueIntentToolDep);
    

    
    
    // ----------------------------------------------
    //   Dialog Begin 非切削移动
    // ----------------------------------------------
    cylinderMillingBuilder->NonCuttingBuilder()->Engage()->SetEngRetType(NXOpen::CAM::NcmHoleMachiningEngRet::EngRetTypesHelical);

    cylinderMillingBuilder->NonCuttingBuilder()->Engage()->MinClearance()->SetValue(80.0);

    cylinderMillingBuilder->NonCuttingBuilder()->Engage()->MinClearance()->SetIntent(NXOpen::CAM::ParamValueIntentToolDep);

    cylinderMillingBuilder->Commit();
    cylinderMillingBuilder->Destroy();





}


```